repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict

  # - repo: https://github.com/adrienverge/yamllint.git
  #   rev: v1.28.0  # Use the latest stable version
  #   hooks:
  #     - id: yamllint
  #       files: \.(yml|yaml)$  # Apply to YAML files only

  # - repo: https://github.com/ansible/ansible-lint
  #   rev: v24.6.0  # Use the latest stable version
  #   hooks:
  #     - id: ansible-lint
  #       files: \.(yml|yaml)$  # Apply to Ansible playbooks and roles

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0  # Use the latest stable version
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]

  - repo: https://github.com/psf/black
    rev: 23.3.0  # Use the latest stable version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Use the latest stable version
    hooks:
      - id: flake8
        args: [--max-line-length=88]

  - repo: https://github.com/PyCQA/isort/
    rev: 5.13.2  # Use the latest stable version
    hooks:
      - id: isort

  # You can add additional hooks here as needed
