---
- name: Install Docker repo
  ansible.builtin.yum_repository:
    name: docker-ce
    baseurl: "{{ docker_repo }}"

- name: Install docker-ce and other packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-compose-plugin

- name: Enable and start docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true
